[project]
name = "mcp-progress-demo"
version = "0.1.0"
description = "MCP Progress Tracking Demo"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.0.0",
    "httpx>=0.25.0",
    "uvicorn>=0.34.3",
    "httpx-sse>=0.4.0",
]

[tool.uv]
dev-dependencies = []
