# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-dev-redis-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-dev-redis
  template:
    metadata:
      labels:
        app: dapr-dev-redis
    spec:
      containers:
      - name: redis
        image: redis:7
        ports:
        - containerPort: 6379
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: dapr-dev-redis-master
  namespace: default
spec:
  selector:
    app: dapr-dev-redis
  ports:
  - port: 6379
    targetPort: 6379