apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-test-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-test-app
  template:
    metadata:
      labels:
        app: dapr-test-app
        version: v1  # Added to trigger pod recreation
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "test-app"
        dapr.io/app-port: "8000"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: app
        image: dapr-test-app:latest
        imagePullPolicy: IfNotPresent  # Explicitly use local image
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dapr-test-app
  namespace: default
spec:
  selector:
    app: dapr-test-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP