apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  tracing:
    samplingRate: "1"  # 100% sampling
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"