# Dapr State Store Component
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: dapr-dev-redis-master:6379
  - name: redisPassword
    value: ""
auth:
  secretStore: kubernetes