apiVersion: v1
kind: Namespace
metadata:
  name: daca
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-app
  namespace: daca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-app
  template:
    metadata:
      labels:
        app: agent-app
    spec:
      containers:
      - name: agent-app
        image: k8s.io/daca-agent:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: agent-app
  namespace: daca
spec:
  selector:
    app: agent-app
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP