services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dapr-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - dapr-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - dapr-network

  chat-service-app:
    build: ./chat_service
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - dapr-network

  chat-service-dapr:
    image: daprio/dapr:1.15.1
    command:
      - "./daprd"
      - "--app-id"
      - "chat-service"
      - "--app-port"
      - "8080"
      - "--dapr-http-port"
      - "3500"
      - "--metrics-port"
      - "9090"
      - "--log-level"
      - "debug"
      - "--resources-path"
      - "/components"
      - "--config"
      - "/components/tracing.yaml"
      - "--app-protocol"
      - "http"
      - "--app-channel-address"
      - "chat-service-app"
    ports:
      - "3500:3500"
    volumes:
      - ./components:/components
    depends_on:
      - chat-service-app
      - redis
      - zipkin
      - prometheus
    networks:
      - dapr-network

  agent-memory-service-app:
    build: ./agent_memory_service
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - dapr-network

  agent-memory-service-dapr:
    image: daprio/dapr:1.15.1
    command:
      - "./daprd"
      - "--app-id"
      - "agent-memory-service"
      - "--app-port"
      - "8001"
      - "--dapr-http-port"
      - "3501"
      - "--metrics-port"
      - "9091"
      - "--log-level"
      - "debug"
      - "--resources-path"
      - "/components"
      - "--config"
      - "/components/tracing.yaml"
      - "--app-protocol"
      - "http"
      - "--app-channel-address"
      - "agent-memory-service-app"
    ports:
      - "3501:3501"
    volumes:
      - ./components:/components
    depends_on:
      - agent-memory-service-app
      - redis
      - zipkin
      - prometheus
    networks:
      - dapr-network

networks:
  dapr-network:
    driver: bridge

volumes:
  redis-data: