[project]
name = "resume-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "httpx-sse>=0.4.0",
    "mcp>=1.9.4",
    "uvicorn>=0.34.3",
]
