[project]
name = "mcp-cancellation-demo"
version = "0.1.0"
description = "MCP Request Cancellation Demo"
readme = "README.md"
dependencies = [
    "fastmcp>=0.4.0",
    "mcp>=0.8.0", 
    "httpx>=0.27.0",
    "uvicorn>=0.30.0",
    "asyncio-mqtt>=0.16.0",
]